[package]
name = "perf"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "~0.9"
thousands = "0.2.0"

[profile.release]
lto = true